import React, { useState } from "react";
import Head from "next/head";
import { MobileNav, Nav } from "@/components/navigation";
import Hero from "@/components/webpages/Hero";

const HomePage = () => {
	const [nav, setNav] = useState(false);
	const openNav = () => setNav(true);
	const closeNav = () => setNav(false);

	return (
		<div className='overflow-x-hidden'>
			<Head>
				<title>Create NextJs TailwindCss Sitemap App</title>
				<meta
					name='description'
					content='Generated by create next-tailwindcss-sitemap app'
				/>
			</Head>
			<div>
				<MobileNav nav={nav} closeNav={closeNav} />
				<Nav openNav={openNav} />
				<Hero />
			</div>
		</div>
	);
};

export default HomePage;
